<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Laporan Pendapatan</title>
    <style>
        body {
            font-family: sans-serif;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #2563eb;
        }

        .header p {
            margin: 5px 0 0;
            font-size: 14px;
            color: #666;
        }

        .summary {
            margin-bottom: 30px;
            padding: 20px;
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
        }

        .summary table {
            width: 100%;
        }

        .summary td {
            padding: 5px;
        }

        .amount {
            font-size: 20px;
            font-weight: bold;
            color: #059669;
        }

        table.data {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
            font-size: 12px;
        }

        table.data th,
        table.data td {
            border: 1px solid #cbd5e1;
            padding: 10px;
            text-align: left;
        }

        table.data th {
            background-color: #f1f5f9;
            color: #475569;
        }

        .text-right {
            text-align: right;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 10px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Laporan Pendapatan</h1>
        <p>SaaS Laundry Management System</p>
    </div>

    <div class="summary">
        <table>
            <tr>
                <td><strong>Periode:</strong><br>{{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} -
                    {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}</td>
                <td class="text-right"><strong>Total Pendapatan:</strong><br><span class="amount">IDR
                        {{ number_format($totalRevenue) }}</span></td>
            </tr>
            <tr>
                <td><strong>Total Tenant Baru:</strong> {{ $tenants->count() }}</td>
                <td class="text-right"><strong>Rata-rata:</strong> IDR
                    {{ $tenants->count() > 0 ? number_format($totalRevenue / $tenants->count()) : 0 }}</td>
            </tr>
        </table>
    </div>

    <table class="data">
        <thead>
            <tr>
                <th>Tanggal</th>
                <th>Nama Tenant</th>
                <th>Owner</th>
                <th>Paket Berlangganan</th>
                <th class="text-right">Biaya (IDR)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($tenants as $tenant)
                <tr>
                    <td>{{ $tenant->created_at->format('d/m/Y H:i') }}</td>
                    <td>{{ $tenant->name }}</td>
                    <td>{{ $tenant->owner_name }}</td>
                    <td>{{ $tenant->subscriptionPackage->name ?? '-' }}</td>
                    <td class="text-right">{{ number_format($tenant->subscriptionPackage->price ?? 0) }}</td>
                </tr>
            @endforeach
            @if($tenants->count() == 0)
                <tr>
                    <td colspan="5" style="text-align: center;">Tidak ada data pada periode ini.</td>
                </tr>
            @endif
        </tbody>
    </table>

    <div class="footer">
        Dicetak pada: {{ now()->format('d M Y H:i') }} | Generated by System
    </div>
</body>

</html>